export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  WHATSAPP: '/dashboard/whatsapp',
  WHATSAPP_STATUS: '/dashboard/whatsapp/status',
  WHATSAPP_CHECKLIST: '/dashboard/whatsapp/checklist',
  CRM: '/dashboard/crm',
  AUTOMATIONS: '/dashboard/automations',
  CAMPAIGNS: '/dashboard/campaigns',
  AI: '/dashboard/ai',
  TEAM: '/dashboard/team',
  REPORTS: '/dashboard/reports',
  BILLING: '/dashboard/billing',
  SETTINGS: '/dashboard/settings',
  ADMIN: '/admin',
} as const;
